import React, { useState, useEffect } from 'react';
import { DollarSign, Landmark, ArrowUpRight, TrendingUp, AlertTriangle } from 'lucide-react';
import saasApi from '@/services/saasApi';

export default function DeveloperRevenue() {
  const [data, setData] = useState<any>({});
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    saasApi.get('/api/v1/marketplace/developer/revenue')
      .then((res) => {
        setData(res.data || {});
      })
      .catch((err) => {
        console.error('Failed to fetch revenue stats:', err);
        setData({}); // Graceful fallback
      })
      .finally(() => {
        setLoading(false);
      });
  }, []);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900 tracking-tight flex items-center gap-2">
          <DollarSign className="w-6 h-6 text-primary-600 animate-pulse" />
          Developer Revenue
        </h1>
        <p className="text-sm text-gray-500 mt-1">Track active subscriptions, platform splits (80/20), and process bank payouts.</p>
      </div>

      {loading ? (
        <div className="text-center py-12 text-gray-400">Loading revenue details...</div>
      ) : (
        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
              <div className="flex justify-between items-start">
                <div>
                  <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider">Gross Revenue</p>
                  <p className="text-3xl font-extrabold text-gray-900 mt-2">${data.gross || '0.00'}</p>
                </div>
                <div className="w-10 h-10 rounded-lg bg-primary-50 flex items-center justify-center text-primary-600 border border-primary-100">
                  <TrendingUp className="w-5 h-5" />
                </div>
              </div>
              <p className="text-[10px] text-gray-400 mt-3 font-semibold">Total revenue generated by apps</p>
            </div>

            <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
              <div className="flex justify-between items-start">
                <div>
                  <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider">Your Profit (80%)</p>
                  <p className="text-3xl font-extrabold text-gray-950 mt-2">${data.net || '0.00'}</p>
                </div>
                <div className="w-10 h-10 rounded-lg bg-emerald-50 flex items-center justify-center text-emerald-600 border border-emerald-100">
                  <DollarSign className="w-5 h-5" />
                </div>
              </div>
              <p className="text-[10px] text-emerald-600 mt-3 font-semibold">Ready for bank transfer</p>
            </div>

            <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
              <div className="flex justify-between items-start">
                <div>
                  <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider">Platform Split (20%)</p>
                  <p className="text-3xl font-extrabold text-gray-500 mt-2">${data.platform || '0.00'}</p>
                </div>
                <div className="w-10 h-10 rounded-lg bg-gray-50 flex items-center justify-center text-gray-400 border border-gray-100">
                  <ArrowUpRight className="w-5 h-5" />
                </div>
              </div>
              <p className="text-[10px] text-gray-400 mt-3 font-semibold">Platform operations split commission</p>
            </div>
          </div>

          {/* Bank Transfer */}
          <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-6">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 rounded-xl bg-primary-50 border border-primary-100 flex items-center justify-center text-primary-700">
                <Landmark className="w-6 h-6" />
              </div>
              <div>
                <h3 className="font-bold text-gray-900 leading-tight">Bank Settlement</h3>
                <p className="text-xs text-gray-400 mt-1">Settlements are processed automatically every Friday to your connected bank account.</p>
              </div>
            </div>
            <button className="bg-primary-600 hover:bg-primary-700 text-white px-5 py-2 rounded-lg text-xs font-semibold shadow-sm transition-all hover:scale-105">
              Request Settlement
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
